- We'll use TensorFlow to build the neural network that tries to predict the total earnings of a new game, based on these characteristics.


- I've gone ahead and split the data into a training data set [sales_data_training.csv]and a test data set [sales_data_test.csv]->  It just  has different data. 


- The machine learning system will only get to see the training data set [sales_data_training.csv] during the training phase.


- Then we'll use this test data to check the accuracy of the predictions from our neural network.

In [6]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Load training data set from CSV file
training_data_df = pd.read_csv('sales_data_training.csv',dtype='float')
print(training_data_df)

     critic_rating  is_action  is_exclusive_to_us  is_portable  \
0              3.5        1.0                 0.0          1.0   
1              4.5        0.0                 0.0          0.0   
2              3.0        0.0                 0.0          0.0   
3              4.5        1.0                 0.0          0.0   
4              4.0        1.0                 0.0          1.0   
5              4.0        0.0                 0.0          0.0   
6              2.0        1.0                 0.0          0.0   
7              4.5        0.0                 0.0          1.0   
8              3.5        0.0                 0.0          1.0   
9              2.5        1.0                 0.0          0.0   
10             4.5        1.0                 0.0          1.0   
11             3.5        0.0                 0.0          0.0   
12             3.5        0.0                 0.0          0.0   
13             4.0        0.0                 0.0          0.0   
14        

In [10]:
# Pull out columns for X (data to train with) and Y (value to predict)


# We pass axis=1 parameter that tells it we want to drop a column and not a row.
#  Finally, we'll call .values to get back the result as an array.

X_training = training_data_df.drop('total_earnings',axis=1).values # Dropping total_earning column from the Data Frame

# Here X_training has all the column except 'total_earnings' column. Since its been dropped

print('X-TRAINING:')
print(X_training)


# Selecting only 'total_earning' column from the dataframe
Y_training = training_data_df[['total_earnings']].values
print('\n\n\nY-TRAINING:')
print(Y_training)


X-TRAINING:
[[  3.5    1.     0.   ...,   0.     0.    59.99]
 [  4.5    0.     0.   ...,   1.     0.    49.99]
 [  3.     0.     0.   ...,   1.     0.    49.99]
 ..., 
 [  4.5    0.     1.   ...,   0.     0.    59.99]
 [  3.5    1.     1.   ...,   0.     1.    39.99]
 [  3.     1.     0.   ...,   0.     1.    49.99]]



Y-TRAINING:
[[ 132717.]
 [  83407.]
 [  62423.]
 [  69889.]
 [ 161382.]
 [  69150.]
 [  62027.]
 [ 152830.]
 [  47930.]
 [  87263.]
 [ 160590.]
 [  67150.]
 [  79844.]
 [  75544.]
 [  96132.]
 [ 115771.]
 [  93173.]
 [ 110544.]
 [ 125506.]
 [ 147129.]
 [  92173.]
 [  65986.]
 [ 140002.]
 [ 111517.]
 [  98605.]
 [ 109594.]
 [  48352.]
 [ 111253.]
 [ 104209.]
 [  59652.]
 [ 157180.]
 [ 109436.]
 [  79316.]
 [  83621.]
 [  98666.]
 [ 144278.]
 [ 105318.]
 [ 187989.]
 [ 112128.]
 [  79345.]
 [  87762.]
 [  35050.]
 [ 100250.]
 [ 109119.]
 [ 155047.]
 [  64611.]
 [ 150336.]
 [ 168351.]
 [  96449.]
 [  75385.]
 [ 104684.]
 [  69467.]
 [ 230275.]
 [  99933.]
 [  96766.]
 [ 12

In [11]:
# Load testing data set from CSV file
test_data_df = pd.read_csv('sales_data_test.csv',dtype='float')

# Pull out columns for X (data to train with) and Y (value to predict)
X_testing = test_data_df.drop('total_earnings',axis=1).values

print('X-TESTING:')
print(X_testing)

Y_testing = test_data_df[['total_earnings']].values
print('\n\n\nY-TESTING:')
print(Y_testing)


X-TESTING:
[[  3.5    1.     1.   ...,   0.     1.    59.99]
 [  2.5    0.     0.   ...,   0.     0.    59.99]
 [  3.5    0.     0.   ...,   1.     0.    59.99]
 ..., 
 [  5.     1.     1.   ...,   0.     0.    39.99]
 [  2.     1.     1.   ...,   0.     0.    39.99]
 [  3.5    1.     0.   ...,   0.     0.    49.99]]



Y-TESTING:
[[ 247537.]
 [  73960.]
 [  82671.]
 [ 137456.]
 [  89639.]
 [ 103734.]
 [  96766.]
 [ 223148.]
 [ 149979.]
 [ 138418.]
 [  96810.]
 [ 122264.]
 [ 101834.]
 [ 126065.]
 [ 138090.]
 [  92173.]
 [ 109436.]
 [  45607.]
 [  97444.]
 [ 105476.]
 [  85838.]
 [ 107157.]
 [ 141427.]
 [  89481.]
 [ 146337.]
 [ 108485.]
 [ 139760.]
 [  82241.]
 [  70001.]
 [ 105182.]
 [  75069.]
 [ 189098.]
 [  82347.]
 [ 196858.]
 [  82558.]
 [  68575.]
 [ 124787.]
 [  68098.]
 [ 162900.]
 [ 234234.]
 [  42862.]
 [  62816.]
 [ 106427.]
 [  58992.]
 [  95332.]
 [  80130.]
 [  46561.]
 [ 246394.]
 [  81502.]
 [ 101359.]
 [  54005.]
 [ 232809.]
 [  87897.]
 [  82347.]
 [  65194.]
 [ 1209

In [13]:
# All data needs to be scaled to a small range like 0 to 1 for the neural
# network to work well. Create scalers for the inputs and outputs.

X_scaler = MinMaxScaler(feature_range=(0,1))
Y_scaler = MinMaxScaler(feature_range=(0,1))

# Scale both the training inputs and outputs
X_scaled_training = X_scaler.fit_transform(X_training)
Y_scaled_training = Y_scaler.fit_transform(Y_training)

print('X_scaled_training')
print(X_scaled_training) # Contains all columns except 'total_earnings' thats been scaled between 0 to 1.
print('\n\n\nY_scaled_training')
print(Y_scaled_training) # Conatins 'total_earning' columns thats been scaled between 0 to 1.

X_scaled_training
[[ 0.5         1.          0.         ...,  0.          0.          1.        ]
 [ 0.83333333  0.          0.         ...,  1.          0.          0.5       ]
 [ 0.33333333  0.          0.         ...,  1.          0.          0.5       ]
 ..., 
 [ 0.83333333  0.          1.         ...,  0.          0.          1.        ]
 [ 0.5         1.          1.         ...,  0.          1.          0.        ]
 [ 0.33333333  1.          0.         ...,  0.          1.          0.5       ]]



Y_scaled_training
[[ 0.37471396]
 [ 0.19242528]
 [ 0.11485185]
 [ 0.14245208]
 [ 0.48068243]
 [ 0.13972015]
 [ 0.11338792]
 [ 0.44906748]
 [ 0.06127428]
 [ 0.2066801 ]
 [ 0.47775457]
 [ 0.13232657]
 [ 0.17925362]
 [ 0.16335742]
 [ 0.23946692]
 [ 0.31206817]
 [ 0.22852812]
 [ 0.29274505]
 [ 0.34805641]
 [ 0.42799209]
 [ 0.22483133]
 [ 0.12802351]
 [ 0.40164507]
 [ 0.29634203]
 [ 0.24860908]
 [ 0.2892331 ]
 [ 0.06283433]
 [ 0.29536607]
 [ 0.26932589]
 [ 0.10460805]
 [ 0.46514852]
 [ 0.288

In [20]:
# The shape attribute for numpy arrays returns the dimensions of the array.

print('Dimensions of X_scaled_testing:',X_scaled_testing.shape)
print(X_scaled_testing.shape[0],'rows','',X_scaled_testing.shape[1],'columns')

print('\n\nDimensions of Y_scaled_testing:',Y_scaled_testing.shape)
print(Y_scaled_testing.shape[0],'rows','',Y_scaled_testing.shape[1],'columns')
print("Note: Y values were scaled by multiplying by {:.10f} and adding {:.4f}".format(Y_scaler.scale_[0], Y_scaler.min_[0]))


Dimensions of X_scaled_testing: (400, 9)
400 rows  9 columns


Dimensions of Y_scaled_testing: (400, 1)
400 rows  1 columns
Note: Y values were scaled by multiplying by 0.0000036968 and adding -0.1159
